repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-toml
          - id: check-yaml
          - id: end-of-file-fixer
            types: [python]
          - id: trailing-whitespace
          - id: requirements-txt-fixer
          - id: check-added-large-files
            args: ["--maxkb=500"]

    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black-jupyter
            language_version: python3.11
